server:
  port: 8080

spring:
  application:
    name: oauth2-server
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
